### ISSUE TITLE
When I run "python3 -m pyprocessing run examples/setupdraw.py" I get an error

### ISSUE THREAD

**Issue by mateusap1** [Dogeek/pyprocessing#5]
The full error:

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mateusap1/Projects/pyprocessing/pyprocessing/__main__.py", line 37, in <module>
    sys.exit(callback(**args))
  File "/home/mateusap1/Projects/pyprocessing/pyprocessing/__main__.py", line 15, in run
    runner = Runner.from_sketch_path(args.path, args.renderers)
AttributeError: 'dict' object has no attribute 'path'
`

When I changed 
`runner = Runner.from_sketch_path(args.path, args.renderers)` to 
`runner = Runner.from_sketch_path(args["path"], args["renderers"])` 
on line 14 of `__main__.py` it worked.

**Comment by PeanutbutterWarrior** [comment]
I'm getting the same error. Changing the line to `runner = Runner.from_sketch_path(path, renderers)` also fixed it

**Comment by PeanutbutterWarrior** [comment]
This was fixed in #7

**Comment by mateusap1** [comment]
Good, I was about to do that.
